services:
  - type: static
    name: furniture-dashboard
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18.x
    rootDir: .
